[versions]
assertj-core = '3.27.6'
junit-jupiter = '6.0.2'
junit-platform-runner = '1.14.2'
mockito-junit-jupiter = '5.21.0'

[libraries]
assertj-core = { module = 'org.assertj:assertj-core', version.ref = 'assertj-core' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit-jupiter' }
junit-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params', version.ref = 'junit-jupiter' }
junit-platform-runner = { module = 'org.junit.platform:junit-platform-runner', version.ref = 'junit-platform-runner' }
mockito-junit-jupiter = { module = 'org.mockito:mockito-junit-jupiter', version.ref = 'mockito-junit-jupiter' }

[plugins]
com-diffplug-spotless = { id = 'com.diffplug.spotless', version = '8.1.0' }
org-owasp-dependencycheck = { id = 'org.owasp.dependencycheck', version = '12.1.9' }
org-kordamp-gradle-java-project = { id = 'org.kordamp.gradle.java-project', version = '0.54.0' }
